### PR TITLE
Additions for ISR names,

### PR DESCRIPTION
**Pull request by mashua**
function call updates on main.

### CODE REVIEW

**Comment by acinonyx** [comment]
LOL. What is the point of creating a pull request if you review and merge it yourself? :P

**Comment by ppapadeas** [comment]
So instead he should merge it to master himself and then push to upstream repo? Nice practice @acinonyx ...

**Comment by acinonyx** [comment]
Obvisously! Please, stop being a victim of the GitHub workflow futility.

**Comment by ppapadeas** [comment]
Then, next time I expect this on an email, not on a comment of a Pull Request. /me drops :microphone:

**Comment by acinonyx** [comment]
I hope there won't be a 'next time'.

**Pull request merged**
